{"uid":"3c8309d69fe184e7","name":"Test Case 19 : Privacy Policy Testing ","fullName":"Tests.HomePage_ContactUs.Footer.test_Footer.TestFooter#test_privacy_policy","historyId":"279075fdf06286a3eb78c4df838f02a4","time":{"start":1689740902974,"stop":1689740902974,"duration":0},"descriptionHtml":"\n    <br><b>Test Case Description:</b>\n    <br><br>Validate the privacy policy is present along with the related content or not .\n    \n    <br><br><b>Expeceted Results:</b>\n    <br><br>Privacy policy should have the policies and procedures.etc.\n    \n    ","status":"broken","statusMessage":"AttributeError: 'TestFooter' object has no attribute 'FooterObj'","statusTrace":"self = <test_Footer.TestFooter object at 0x7f4f85e232b0>\n\n    @allure.title(\"Test Case 19 : Privacy Policy Testing \")\n    @allure.description_html(\"\"\"\n    <br><b>Test Case Description:</b>\n    <br><br>Validate the privacy policy is present along with the related content or not .\n    \n    <br><br><b>Expeceted Results:</b>\n    <br><br>Privacy policy should have the policies and procedures.etc.\n    \n    \"\"\")\n    def test_privacy_policy(self):\n        try:\n>           privacy_policy = TestFooter.FooterObj.get_privacy_policy_status()\nE           AttributeError: type object 'TestFooter' has no attribute 'FooterObj'\n\nTests/HomePage_ContactUs/Footer/test_Footer.py:138: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_Footer.TestFooter object at 0x7f4f85e232b0>\n\n    @allure.title(\"Test Case 19 : Privacy Policy Testing \")\n    @allure.description_html(\"\"\"\n    <br><b>Test Case Description:</b>\n    <br><br>Validate the privacy policy is present along with the related content or not .\n    \n    <br><br><b>Expeceted Results:</b>\n    <br><br>Privacy policy should have the policies and procedures.etc.\n    \n    \"\"\")\n    def test_privacy_policy(self):\n        try:\n            privacy_policy = TestFooter.FooterObj.get_privacy_policy_status()\n            assert privacy_policy\n        except:\n>           allure.attach(self.FooterObj.driver.get_screenshot_as_png(),name=\"Footer Element Error\", attachment_type= allure.attachment_type.PNG)\nE           AttributeError: 'TestFooter' object has no attribute 'FooterObj'\n\nTests/HomePage_ContactUs/Footer/test_Footer.py:141: AttributeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"init_driver","time":{"start":1689740601210,"stop":1689740602883,"duration":1673},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[{"name":"init_driver::0","time":{"start":1689740902986,"stop":1689740903039,"duration":53},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('init_driver')"},{"name":"parentSuite","value":"Tests.HomePage_ContactUs.Footer"},{"name":"suite","value":"test_Footer"},{"name":"subSuite","value":"TestFooter"},{"name":"host","value":"isadmin"},{"name":"thread","value":"8101-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Tests.HomePage_ContactUs.Footer.test_Footer"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('init_driver')"]},"source":"3c8309d69fe184e7.json","parameterValues":[]}