{"uid":"62fbb8b182013124","name":"Test Case 15 : Recent Post Visibility Testing","fullName":"Tests.HomePage_ContactUs.Footer.test_Footer.TestFooter#test_recent_post","historyId":"aaee677c7c3c4acd9158d653f8054a75","time":{"start":1689740902953,"stop":1689740902953,"duration":0},"descriptionHtml":"\n    <br><b>Test Case Description:</b>\n    <br><br>Validate the footer page is having updated posts \n    \n    <br><br><b>Expeceted Results:</b>\n    <br><br>Updated posts is should give the update regarding seminar related, blogs,notification \n    \n    ","status":"broken","statusMessage":"AttributeError: 'TestFooter' object has no attribute 'FooterObj'","statusTrace":"self = <test_Footer.TestFooter object at 0x7f4f85e22e30>\n\n    @allure.title(\"Test Case 15 : Recent Post Visibility Testing\")\n    @allure.description_html(\"\"\"\n    <br><b>Test Case Description:</b>\n    <br><br>Validate the footer page is having updated posts\n    \n    <br><br><b>Expeceted Results:</b>\n    <br><br>Updated posts is should give the update regarding seminar related, blogs,notification\n    \n    \"\"\")\n    def test_recent_post(self):\n        try:\n>           recent_post_visibility_status = TestFooter.FooterObj.get_recent_post_status()\nE           AttributeError: type object 'TestFooter' has no attribute 'FooterObj'\n\nTests/HomePage_ContactUs/Footer/test_Footer.py:76: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_Footer.TestFooter object at 0x7f4f85e22e30>\n\n    @allure.title(\"Test Case 15 : Recent Post Visibility Testing\")\n    @allure.description_html(\"\"\"\n    <br><b>Test Case Description:</b>\n    <br><br>Validate the footer page is having updated posts\n    \n    <br><br><b>Expeceted Results:</b>\n    <br><br>Updated posts is should give the update regarding seminar related, blogs,notification\n    \n    \"\"\")\n    def test_recent_post(self):\n        try:\n            recent_post_visibility_status = TestFooter.FooterObj.get_recent_post_status()\n            assert recent_post_visibility_status\n        except:\n>           allure.attach(self.FooterObj.driver.get_screenshot_as_png(),name=\"Footer Element Error\", attachment_type= allure.attachment_type.PNG)\nE           AttributeError: 'TestFooter' object has no attribute 'FooterObj'\n\nTests/HomePage_ContactUs/Footer/test_Footer.py:79: AttributeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"init_driver","time":{"start":1689740601210,"stop":1689740602883,"duration":1673},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[{"name":"init_driver::0","time":{"start":1689740902986,"stop":1689740903039,"duration":53},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('init_driver')"},{"name":"parentSuite","value":"Tests.HomePage_ContactUs.Footer"},{"name":"suite","value":"test_Footer"},{"name":"subSuite","value":"TestFooter"},{"name":"host","value":"isadmin"},{"name":"thread","value":"8101-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Tests.HomePage_ContactUs.Footer.test_Footer"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('init_driver')"]},"source":"62fbb8b182013124.json","parameterValues":[]}